### ISSUE TITLE
Page order should follow the new page specification.

### ISSUE THREAD

**Issue by JJ** [antoniogamiz/Perl6-Documentable#51]
In general, we will try to keep metadata as close to the file as possible, so in the file specification document it states that page order (actually, grouping in classes) should be specified as file metadata.
Maybe transitionally a flag for using one or the other should be used, but the file order document right now is in a different format, so that is that one that should be used.

**Comment by JJ** [comment]
Also, doing something else than first generating source files and then doing something else would speed this up a lot.

**Comment by antoniogamiz** [comment]
Mmm, do you mind to explain what's the new page specification? Or send me a link where it's described. I have changed the format of the previous file because I have got rid of `manage-page-order.p6`. In addition, I do not know why to use a specific format when JSON covers almost all use cases.

**Comment by antoniogamiz** [comment]
Any update?
