### ISSUE TITLE
Apparently, you can create a documentable without an actual document

### ISSUE THREAD

**Issue by JJ** [antoniogamiz/Perl6-Documentable#56]
**Describe the bug**

Tests for Documentable do not use an actual document. That's probably an error.

**To Reproduce**

**Expected behavior**

Probably the relationship between attributes and their existence should be enforced at the build level.

**Comment by antoniogamiz** [comment]
Only 3 tests did not use a document because none was needed to test that part. Anyway, I have made $.pod mandatory.

**Comment by antoniogamiz** [comment]
This was fixed in ce038362889f26a9305e08091f4b52724bea676f as a result of the new hierarchy, so I will close this.
