### ISSUE TITLE
Refactor Utils

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/Perl6-Documentable#57]
Utils is quite a mess. I have added there all kind of functions that I did not know where to put.

I'm going to create two modules:

- Perl6::Utils::Filesystem => to get pod names, read dirs and that kind of things.
- Perl6::Utils::Logger => a good logging system.

**Comment by JJ** [comment]
Are you going to create them _here_?

**Comment by antoniogamiz** [comment]
Mmmm yes? I do not know where else should be placed.

**Comment by JJ** [comment]
Closest to where they are used...
