### ISSUE TITLE
Perl6::Documentable v2.1.0 fails to install

### ISSUE THREAD

**Issue by noisegul** [antoniogamiz/Perl6-Documentable#75]
Since installing `2.1.0` fails due to tests, could you prepare another release with the fixing changes?

Makes it easier to update and work with than `master`.

For reference, my [error is the same as the one in CI](https://travis-ci.org/antoniogamiz/Perl6-Documentable/builds/567502340).

**Comment by antoniogamiz** [comment]
Fixed.

**Comment by noisegul** [comment]
Thanks.

**Comment by JJ** [comment]
Thanks both. You are doing a great job
