### ISSUE TITLE
Versions don't match for v2.1.1

### ISSUE THREAD

**Issue by noisegul** [antoniogamiz/Perl6-Documentable#78]
For the `2.1.1` release, the version unfortunately doesn't match with the [version specified](https://github.com/antoniogamiz/Perl6-Documentable/blob/60a5bc0b6e58af407d4e5198a448e38a5f1c3e03/META6.json#L61) in it's `META6.json` file, where it's still `2.1.0`, so I can't pin the version and install it from the [releases](https://github.com/antoniogamiz/Perl6-Documentable/releases).

Could you prepare another github release with matching versions?

**Comment by antoniogamiz** [comment]
Fixed, sorry for the troubles, I forgot to change META6.

**Comment by noisegul** [comment]
No problem at all, thanks for the quick fix!

**Comment by JJ** [comment]
If you use Mi6 it will do that for you.

**Comment by antoniogamiz** [comment]
Mmm can you explain how? I have taken a look at the """docs""" and I have not found anything.
