### ISSUE TITLE
Cannot install with test

### ISSUE THREAD

**Issue by finanalyst** [antoniogamiz/Perl6-Documentable#85]
**Describe the bug**
Installation using zef fails, but if -/test is given, then passes

What am I missing?

**To Reproduce**
in directory linked to this repo
```
~/development/perl6-documentable$ git pull 
Already up to date.
~/development/perl6-documentable$ zef --force install .
===> Testing: Perl6::Documentable:ver<2.1.3>:auth<Perl6 Team>:api<2>
Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /home/richard/rakudo/install/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /home/richard/development/perl6-documentable/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/301-registry.t line 9

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /home/richard/rakudo/install/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /home/richard/development/perl6-documentable/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/303-process-pod-dir.t line 8

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /home/richard/rakudo/install/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /home/richard/development/perl6-documentable/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/304-compose-type.t line 8

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /home/richard/rakudo/install/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /home/richard/development/perl6-documentable/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/305-search.t line 7

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /home/richard/rakudo/install/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /home/richard/development/perl6-documentable/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/306-index.t line 8

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /home/richard/rakudo/install/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /home/richard/development/perl6-documentable/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/401-indexes.t line 8

===> Testing [FAIL]: Perl6::Documentable:ver<2.1.3>:auth<Perl6 Team>:api<2>
Failed to get passing tests, but continuing with --force-test
===> Installing: Perl6::Documentable:ver<2.1.3>:auth<Perl6 Team>:api<2>

1 bin/ script [documentable] installed to:
/home/richard/rakudo/install/share/perl6/site/bin

~/development/perl6-documentable$ zef --force -/test install .
===> Installing: Perl6::Documentable:ver<2.1.3>:auth<Perl6 Team>:api<2>

1 bin/ script [documentable] installed to:
/home/richard/rakudo/install/share/perl6/site/bin
```

**Expected behavior**
No test errors

**Desktop (please complete the following information):**
```
uname -a
Linux merlin 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```

**Additional context**

**Comment by antoniogamiz** [comment]
I think this problem is related to #48 . Can you please check the version of `Perl6::TypeGraph`? It should be the `0.0.4`. CI tests are passing, so the problem must be something related to Rakudo Star.

**Comment by noisegul** [comment]
I also recently noticed that `Perl6::Documentable::Registry` fails when using Rakudo Star, I too think it's related to #48, I can also confirm that everything appears to work with regular Rakudo.

@antoniogamiz I saw in the META6.json that TypeGraph version `0.0.4` is listed under `test-depends`, but not in `depends`:

```
  "depends": [
    "Pod::Load:ver<0.5.4>",
    "Pod::To::HTML:ver<0.6.1>",
    "Pod::To::Cached:ver<0.3.2>",
    "Pod::Utilities:ver<0.0.1>",
    "URI:ver<0.2.2>",
    "File::Temp:ver<0.0.6>",
    "Log::Timeline:ver<0.3>"
  ],
```

Maybe that can fix the problems when installing and using it with Rakudo Star by ensuring
the right version?

Also @finanalyst, can you tell us the zef version you were using?

**Comment by antoniogamiz** [comment]
Good catch @noisegul , I wil correct that right now, I did not realize. Thanks.

**Comment by antoniogamiz** [comment]
I have changed it, please check it out now. And @noisegul, could you give additional information about the problems with `Perl6::Documentable::Registry`?

**Comment by noisegul** [comment]
Should have been the same error as above, so this might have already fixed it. Otherwise I'll prepare an example after giving it a try.

**Comment by noisegul** [comment]
Also thanks for the release @antoniogamiz

**Comment by noisegul** [comment]
Ok I gave it a try:

```
$ zef install https://github.com/antoniogamiz/Perl6-Documentable/archive/v2.1.4.tar.gz
===> Testing: Perl6::Documentable:ver<2.1.4>:auth<Perl6 Team>:api<2>
Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /usr/local/Cellar/rakudo-star/2019.03/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /Users/tester/.zef/store/v2.1.4.tar.gz/Perl6-Documentable-2.1.4/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/301-registry.t line 9

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /usr/local/Cellar/rakudo-star/2019.03/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /Users/tester/.zef/store/v2.1.4.tar.gz/Perl6-Documentable-2.1.4/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/303-process-pod-dir.t line 8

Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /usr/local/Cellar/rakudo-star/2019.03/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /Users/tester/.zef/store/v2.1.4.tar.gz/Perl6-Documentable-2.1.4/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/304-compose-type.t line 8
[...snip...]
```

Upgrading first:
```
$ zef update
$ zef nuke StoreDir
$ zef upgrade
```

Trying again after upgrading:
```
$ zef install https://github.com/antoniogamiz/Perl6-Documentable/archive/v2.1.4.tar.gz
===> Testing: Perl6::Documentable:ver<2.1.4>:auth<Perl6 Team>:api<2>
Too few positionals passed; expected 2 arguments but got 1
  in method new-from-file at /usr/local/Cellar/rakudo-star/2019.03/share/perl6/site/sources/BE2CAF04F8CDB952CB4722F9862EDD347DD13CC0 (Perl6::TypeGraph) line 29
  in submethod BUILD at /Users/tester/.zef/store/v2.1.4.tar.gz/Perl6-Documentable-2.1.4/lib/Perl6/Documentable/Registry.pm6 (Perl6::Documentable::Registry) line 40
  in block <unit> at t/301-registry.t line 9
[...snip...]
```

Taking a look at Perl6::TypeGraph, looks like the wrong version:
```
$ zef info Perl6::TypeGraph
- Info for: Perl6::TypeGraph
- Identity: p6doc:ver<1.002001>
- Recommended By: /usr/local/Cellar/rakudo-star/2019.03/share/perl6/site
- Installed: Yes
Description:	 Perl 6 documentation (tools and docs)
License:	 Artistic-2.0
Source-url:	 git://github.com/perl6/doc.git
Provides: 10 modules
Support:
#   source:	git://github.com/perl6/doc.git
Depends: 9 items
```

The problem here appears to be that `Perl6::TypeGraph` is part of perl6/doc which is bundled together with Rakudo Star, so it can't be uninstalled, upgraded or installed independently, because it is part of [perl6/doc](https://github.com/perl6/doc) which is on top of that registered under the identity `p6doc` (not to be confused with just `p6doc` the command/tool, which is currently also still a *part* of perl6/doc as it's distributed with Rakudo Star).

Which should be why everything works fine with plain Rakudo, but not with Rakudo Star.

**Comment by antoniogamiz** [comment]
Mmmm, then is a bigger problem. `Perl6::TypeGraph` is separated from `perl6/doc` (at this moment).

So the only solution is that Rakudo Star distribution updates its instance of `perl6/doc`.

**Comment by noisegul** [comment]
Looks like it, with the current situation, if a user wanted to try out either 'new' p6doc or Perl6::Documentable he would have to either

- Use plain Rakudo.
- Wait for another Rakudo Star release shipping with a `perl6/doc` version in which `Perl6::TypeGraph` is already separated.
- Update `perl6/doc` themselves to a newer version (probably *not* recommended because that could obviously lead to other kinds of problems since Rakudo Star bundles a lot of stuff)

So it's not really a problem or bug with Perl6::Documentable, but rather a mere side effect of splitting out modules that were shipped in the bundle before.

Am I missing something?

**Comment by finanalyst** [comment]
We need to rename in some way TypeGraph so that it is clearly distinguished from the Rakudo-Star version.

I note that Antonio's Documentable has `"api": 2` in the Meta.json. Since Documentable is also in Rakudo-Star, is this sufficient for zef to distinguish between the two?

If so, then add "api": 2 to TypeGraph's Meta.json.

We do need to make sure that the new version of p6doc works with all reasonably recent versions of Rakudo Star.

If all this fails, then we may need to rename Antonio's TypeGraph module completely. However, before we do this, Antonio should go onto IRC #perl6 and ask the community for the best strategy to distinguish that the new version of Documentable accesses the correct version of TypeGraph

**Comment by finanalyst** [comment]
The sequence 
```
zef update
zef nuke StoreDir
zef upgrade
```
created quite a few error messages, making me think it had disrupted my system!! This is not to be recommended! For instance, I got an error installing Data::Dump !!!

Also I got a test error installing Pod::To::Cached:v<0.3.3>

Since I had just updated Pod::To::Cached and bumped the version to 0.3.3, and I had no local problems with P2Cached, I installed locally again with zef. No problem.  I also upgraded Data::Dump separately, no problem.

Next time I ran
```
zef update
zef nuke StoreDir
zef upgrade
```
there were no problems with Data::Dump or Pod::To::Cached.

There remain problems with Documentable tracing back to TypeGraph, as Joel has pointed out.

If `zef nuke StoreDir` is mentioned in documentation, then there should be some description of possible problems.

**Comment by antoniogamiz** [comment]
I'm trying to test if your solution work. I have already released a new version of TypeGraph to test it. I'm currently waiting for the cache of zef to be updated.

**Comment by finanalyst** [comment]
I think I have solved this. 

The problem is that zef has Perl6::TypeGraph listed as version = 1.002001, this is from Rakudo-Star. It comes from the p6doc installation there.

Antonio's version has version = 0.1.0

So The Rakudo-Star version is greater than Antonio's version.

Bump version to 2.0.0 in Antonio's version, and then it all works correctly.

I am about to commit the change (also there is a typo in the latest version of META6, no 'ver' is included in Pod::To::Cached)

**Comment by antoniogamiz** [comment]
Agh, I hate when I make that kind of mistakes, sorry. I do not know why `Test::META` has not detected that.

Why do you say "Antonio's version has version = 0.1.0"? The last version of TypeGraph was 0.0.4, and now 0.0.5.
