### ISSUE TITLE
Support for multiple highlighters

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/Perl6-Documentable#89]
Currently we only support the perl6-atom-highlighter, but there's other like https://github.com/stmuk/p6-Text-VimColour, which needs less setup. So we should add it.

The highlighter should be passed to DocPage::Factory in the constructor.

**Comment by finanalyst** [comment]
Yes, I am in favour of adding the possibility of another highlighter. But from what I can see, the atom highlighter has the most work being done for perl6, so it should remain the default.

**Comment by antoniogamiz** [comment]
Ok :).

**Comment by antoniogamiz** [comment]
As I have said in #97 , a new docker container is being used with the necessary setup for highlighting. I have seen the results of Text-VimColour in https://examples.p6c.dev/categories/perlmonks/weighted-roll-731696.html and I dont like the result. 

I think that with the new setup is quite easy to enable highlighting so this is no longer needed, I will close it. Reopen if you think it's necessary.
