### ISSUE TITLE
Breaking changes, no working release version

### ISSUE THREAD

**Issue by noisegul** [antoniogamiz/Perl6-Documentable#95]
Version `2.1.4` and post `2.2.0` are not compatible.

Looks like Perl6::Documentable::File was renamed to Perl6::Documentable::Primary?
The documentation is not yet updated, so I have to ask: Are there other breaking changes to note, or coming?

Also: Normally I'd simply wait until the bigger changes are done (and reflected in the documentation), but the changes to Pod::To::Cached and Perl6::TypeGraph versioning apparently also makes Perl6::Documentable `2.1.4` uninstallable via zef:

```
Failed to find dependencies: Pod::To::Cached:ver<0.3.2>, Perl6::TypeGraph:ver<0.0.4>
```

This leaves me without a working Perl6::Documentable version (2.2.0 does not yet include the updated dependencies inside it's META6.json).

Could you prepare another release?

**Comment by antoniogamiz** [comment]
I will do it right now. 

Tough Typegraph should be found, because I made independent releases in GitHub. I though 'zef' was able to look at the tags of a repository to find specific version of a module. Maybe I'm wrong, I will check that with @ugexe.

Due to the "periodicity" of the problems with versions in these two modules, I will add the '+' symbol in the version requirement to avoid future inconveniences.

**Comment by antoniogamiz** [comment]
There's a new version already published. It will take a couple of hours for zef to update the cache. As for the documentation, there's an updated version here => https://antoniogamiz.github.io/Perl6-Documentable/. It's autodeployed when I add something new. I will complete it with examples and guides during the week.

Please let me know if it works now.

**Comment by noisegul** [comment]
Works now. Much appreciated.

**Comment by JJ** [comment]
El mar., 13 ago. 2019 a las 19:32, Joel (<notifications@github.com>)
escribió:

> Version 2.1.4 and post 2.2.0 are not compatible.
>
> Looks like Perl6::Documentable::File was renamed to
> Perl6::Documentable::Primary?
> The documentation is not yet updated, so I have to ask: Are there other
> breaking changes to note, or coming?
>

Probably renaming should be accompanied by a change in major version as
well as a change in API version.

**Comment by antoniogamiz** [comment]
I will update the version to 3.0.0 then.
